//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSpiritualDimension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheSpiritualDimension.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplico este codigo sagrado para.
        /// </summary>
        internal static string AplicoCodigo {
            get {
                return ResourceManager.GetString("AplicoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplico este numero de Grabovoi para .
        /// </summary>
        internal static string AplicoGrabovoi {
            get {
                return ResourceManager.GetString("AplicoGrabovoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Benidiciones!.
        /// </summary>
        internal static string Bendiciones {
            get {
                return ResourceManager.GetString("Bendiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .En beneficio de.
        /// </summary>
        internal static string beneficiode {
            get {
                return ResourceManager.GetString("beneficiode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta invocación ha sido para el beneficio de.
        /// </summary>
        internal static string hasidopara {
            get {
                return ResourceManager.GetString("hasidopara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me relajo y realizo 3 inhalaciones profundas.
        /// </summary>
        internal static string Merelajo {
            get {
                return ResourceManager.GetString("Merelajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  y en nombre de la poderosa presencia yo soy invoco el código sagrado de sanación .
        /// </summary>
        internal static string poderosapresencia {
            get {
                return ResourceManager.GetString("poderosapresencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca el número sagrado que quiera invocar..
        /// </summary>
        internal static string Porfavorintroduzca {
            get {
                return ResourceManager.GetString("Porfavorintroduzca", resourceCulture);
            }
        }
    }
}
